[tool.poetry]
name = "brain-mri-segmentation"
version = "0.2.0"
description = "2D and 3D brain MRI tissue segmentation using traditional computer vision techniques (active contours, thresholding, clustering) with comprehensive evaluation on 6 tissue classes."
authors = ["iamivan11"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "*"
matplotlib = "*"
opencv-python = "*"
scipy = "*"
scikit-learn = "*"
scikit-image = "*"
threadpoolctl = "*"
ipykernel = {version = "^7.1.0", python = ">=3.10"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[dependency-groups]
dev = [
    "pre-commit (>=4.5.1,<5.0.0)"
]
